# Organization-specific LiteLLM Proxy config

model_list:
  # OpenAI Models
  - model_name: "gpt-4o"
    litellm_params:
      model: "gpt-4o"
      api_key: os.environ/OPENAI_API_KEY

  - model_name: "gpt-4o-mini"
    litellm_params:
      model: "gpt-4o-mini"
      api_key: os.environ/OPENAI_API_KEY

  - model_name: "gpt-4-turbo"
    litellm_params:
      model: "gpt-4-turbo"
      api_key: os.environ/OPENAI_API_KEY

  - model_name: "gpt-4-turbo-preview"
    litellm_params:
      model: "gpt-4-turbo-preview"
      api_key: os.environ/OPENAI_API_KEY

  - model_name: "gpt-4"
    litellm_params:
      model: "gpt-4"
      api_key: os.environ/OPENAI_API_KEY

  - model_name: "gpt-4-32k"
    litellm_params:
      model: "gpt-4-32k"
      api_key: os.environ/OPENAI_API_KEY

  - model_name: "gpt-3.5-turbo"
    litellm_params:
      model: "gpt-3.5-turbo"
      api_key: os.environ/OPENAI_API_KEY

  - model_name: "gpt-3.5-turbo-16k"
    litellm_params:
      model: "gpt-3.5-turbo-16k"
      api_key: os.environ/OPENAI_API_KEY

  - model_name: "gpt-3.5-turbo-instruct"
    litellm_params:
      model: "gpt-3.5-turbo-instruct"
      api_key: os.environ/OPENAI_API_KEY

  - model_name: "text-davinci-003"
    litellm_params:
      model: "text-davinci-003"
      api_key: os.environ/OPENAI_API_KEY

  - model_name: "text-davinci-002"
    litellm_params:
      model: "text-davinci-002"
      api_key: os.environ/OPENAI_API_KEY

  - model_name: "text-curie-001"
    litellm_params:
      model: "text-curie-001"
      api_key: os.environ/OPENAI_API_KEY

  - model_name: "text-babbage-001"
    litellm_params:
      model: "text-babbage-001"
      api_key: os.environ/OPENAI_API_KEY

  - model_name: "text-ada-001"
    litellm_params:
      model: "text-ada-001"
      api_key: os.environ/OPENAI_API_KEY

  - model_name: "dall-e-3"
    litellm_params:
      model: "dall-e-3"
      api_key: os.environ/OPENAI_API_KEY

  - model_name: "dall-e-2"
    litellm_params:
      model: "dall-e-2"
      api_key: os.environ/OPENAI_API_KEY

  - model_name: "whisper-1"
    litellm_params:
      model: "whisper-1"
      api_key: os.environ/OPENAI_API_KEY

  - model_name: "tts-1"
    litellm_params:
      model: "tts-1"
      api_key: os.environ/OPENAI_API_KEY

  - model_name: "tts-1-hd"
    litellm_params:
      model: "tts-1-hd"
      api_key: os.environ/OPENAI_API_KEY

  - model_name: "text-embedding-ada-002"
    litellm_params:
      model: "text-embedding-ada-002"
      api_key: os.environ/OPENAI_API_KEY

  - model_name: "text-embedding-3-small"
    litellm_params:
      model: "text-embedding-3-small"
      api_key: os.environ/OPENAI_API_KEY

  - model_name: "text-embedding-3-large"
    litellm_params:
      model: "text-embedding-3-large"
      api_key: os.environ/OPENAI_API_KEY

  # Anthropic Models
  - model_name: "claude-3-5-sonnet"
    litellm_params:
      model: "anthropic/claude-3-5-sonnet"
      api_key: os.environ/ANTHROPIC_API_KEY

  - model_name: "claude-3-5-haiku"
    litellm_params:
      model: "anthropic/claude-3-5-haiku"
      api_key: os.environ/ANTHROPIC_API_KEY

  - model_name: "claude-3-opus"
    litellm_params:
      model: "anthropic/claude-3-opus"
      api_key: os.environ/ANTHROPIC_API_KEY

  - model_name: "claude-3-sonnet"
    litellm_params:
      model: "anthropic/claude-3-sonnet"
      api_key: os.environ/ANTHROPIC_API_KEY

  - model_name: "claude-3-haiku"
    litellm_params:
      model: "anthropic/claude-3-haiku"
      api_key: os.environ/ANTHROPIC_API_KEY

  - model_name: "claude-2.1"
    litellm_params:
      model: "anthropic/claude-2-1"
      api_key: os.environ/ANTHROPIC_API_KEY

  - model_name: "claude-2.0"
    litellm_params:
      model: "anthropic/claude-2-0"
      api_key: os.environ/ANTHROPIC_API_KEY

  - model_name: "claude-instant-1.2"
    litellm_params:
      model: "anthropic/claude-instant-1-2"
      api_key: os.environ/ANTHROPIC_API_KEY

  - model_name: "claude-instant-1.1"
    litellm_params:
      model: "anthropic/claude-instant-1-1"
      api_key: os.environ/ANTHROPIC_API_KEY

  - model_name: "claude-1.3"
    litellm_params:
      model: "anthropic/claude-1-3"
      api_key: os.environ/ANTHROPIC_API_KEY

  - model_name: "claude-1.2"
    litellm_params:
      model: "anthropic/claude-1-2"
      api_key: os.environ/ANTHROPIC_API_KEY

  - model_name: "claude-1.1"
    litellm_params:
      model: "anthropic/claude-1-1"
      api_key: os.environ/ANTHROPIC_API_KEY

  - model_name: "claude-1.0"
    litellm_params:
      model: "anthropic/claude-1-0"
      api_key: os.environ/ANTHROPIC_API_KEY

  # Example Azure mapping (keeping existing)
  - model_name: "gpt-4o-azure"
    litellm_params:
      model: "azure/gpt-4o"
      api_key: os.environ/AZURE_API_KEY
      api_base: os.environ/AZURE_API_BASE
      api_version: os.environ/AZURE_API_VERSION

litellm_settings:
  telemetry: false
  request_timeout: 600
  num_retries: 5
  drop_params: true

router_settings:
  routing_strategy: usage-based-routing-v2
  # redis_host: os.environ/REDIS_HOST
  # redis_password: os.environ/REDIS_PASSWORD
  # redis_port: os.environ/REDIS_PORT

general_settings:
  master_key: os.environ/LITELLM_MASTER_KEY
  store_model_in_db: true  # enable adding models at runtime via UI/API
  # database_url: os.environ/DATABASE_URL  # if you want to override env

# Optional pass-through example
# general_settings:
#   pass_through_endpoints:
#     - path: "/v1/rerank"
#       target: "https://api.cohere.com/v1/rerank"
#       headers:
#         content-type: application/json
#         accept: application/json
#       forward_headers: true
